# Generated by Django 2.2.6 on 2020-11-26 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_auto_20201125_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Описагие группы',
                                   verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(
                help_text=('Укажите адрес для страницы задачи. Используйте ' +
                           'только латиницу, цифры, дефисы и знаки ' +
                           'подчёркивания'), null=True, unique=True,
                verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Название группы',
                                   max_length=200, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                help_text='Это поле заполняется автоматически',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts', to=settings.AUTH_USER_MODEL,
                verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(
                blank=True,
                help_text='Не обязательное поле',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='posts', to='posts.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Дата указывается автоматически',
                verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите здесь что-нибудь',
                                   verbose_name='Текст поста'),
        ),
    ]
