# Generated by Django 2.2.6 on 2020-12-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_auto_20201202_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True,
                help_text='Дата указывается автоматически',
                verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True,
                help_text='Дата указывается автоматически',
                verbose_name='Дата публикации'),
        ),
    ]
